/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Usuario;

/**
 *
 * @author Usuario
 */
public class VChat extends javax.swing.JPanel {

    /**
     * Creates new form VChat
     * @param usuario1
     * @param usuario2
     */
    
    Usuario usuario1, usuario2;
    ArrayList <String> mensajes = new ArrayList();
    private boolean flagNuevaConversacion = true;
    DefaultListModel modelo;
    VAmigos VPadre;
    int indice;
    
    public VChat(Usuario usuario1, Usuario usuario2, VAmigos VPadre) {
        initComponents();
        this.nombreUsuario.setText(usuario2.getNombreUsuario());
        this.usuario1=usuario1;
        this.usuario2=usuario2;
        modelo = new DefaultListModel();
        this.VPadre=VPadre;
        this.indice = 0;
    }
    
     public VChat(Usuario usuario1, Usuario usuario2, String mensaje, VAmigos VPadre) throws RemoteException {
        initComponents();
        this.nombreUsuario.setText(usuario2.getNombreUsuario());
        this.usuario1=usuario1;
        this.usuario2=usuario2;
        modelo = new DefaultListModel();
        mostrarMensaje(usuario2.getNombreUsuario(), mensaje);
        this.VPadre= VPadre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        fieldMensaje = new javax.swing.JTextArea();
        botonArchivo = new javax.swing.JButton();
        botonEnviar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMensajes = new javax.swing.JList<>();
        nombreUsuario = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        fieldMensaje.setColumns(20);
        fieldMensaje.setRows(5);
        jScrollPane1.setViewportView(fieldMensaje);

        botonArchivo.setText("Archivo");
        botonArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArchivoActionPerformed(evt);
            }
        });

        botonEnviar.setText("Enviar");
        botonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(listaMensajes);

        nombreUsuario.setForeground(new java.awt.Color(0, 153, 0));
        nombreUsuario.setText("nombreUsuario");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/circuloVerde.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(nombreUsuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonArchivo)
                        .addGap(17, 17, 17)
                        .addComponent(botonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarActionPerformed
        try {
            String mensaje = this.fieldMensaje.getText();
            this.fieldMensaje.setText("");
            this.usuario2.getCliente().recbirMensaje(this.usuario1, mensaje);
            mostrarMensaje(this.usuario1.getNombreUsuario(),mensaje);
        } catch (RemoteException ex) {
            Logger.getLogger(VChat.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonEnviarActionPerformed

    private void botonArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION){
            File archivo = fileChooser.getSelectedFile();
            try {
                this.usuario2.getCliente().recibirArchivo(this.usuario1, archivo);
            } catch (RemoteException ex) {
                Logger.getLogger(VChat.class.getName()).log(Level.SEVERE, null, ex);
            }
            mostrarArchivo(this.usuario1.getNombreUsuario(),archivo);
            
        }
//        else if(returnValue == JFileChooser.CANCEL_OPTION){
//            
//        }
    }//GEN-LAST:event_botonArchivoActionPerformed
   
    public void mostrarArchivo (String usuario, File archivo){
        String mensajeFinal = "[" + usuario + "] ha enviado el archivo [" + archivo.getName() + "]";   
        modelo.addElement(mensajeFinal);
        listaMensajes.setModel(modelo);
    }
    
    public void descargarArchivo(File archivo) throws IOException{
        
        int opcion = JOptionPane.showConfirmDialog(new JPanel(), this.usuario2.getNombreUsuario() + " te está intentando enviar un archivo. Quieres descargarlo? "
                + "(Nombre del archivo: " + archivo.getName() + ")", "Aviso", JOptionPane.YES_NO_OPTION);
        
        if ( opcion == JOptionPane.YES_OPTION) {
            byte[] data = Files.readAllBytes(archivo.toPath());
        
        String extension = "";

        int i = archivo.getName().lastIndexOf('.');
        if (i > 0) {
            extension = archivo.getName().substring(i+1);
        }
        
        File file = new File("D:\\archivode" + this.usuario2.getNombreUsuario() + "." + extension);
       
        while(file.exists()){
            indice ++;
            file = new File("D:\\archivode" + this.usuario2.getNombreUsuario() + indice + "." + extension);
        }
        
        OutputStream out = new FileOutputStream(file);
        out.write(data);
        out.close();
        
        String mensajeFinal = "Se ha descargado el el archivo [" + archivo.getName() + "] de " + this.usuario2.getNombreUsuario();   
        modelo.addElement(mensajeFinal);
        listaMensajes.setModel(modelo);    
}             
    }
    
    public void mostrarMensaje(String usuario, String mensaje) throws RemoteException{
        String mensajeFinal = "[" + usuario + "] " + mensaje;   
        modelo.addElement(mensajeFinal);
        listaMensajes.setModel(modelo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonArchivo;
    private javax.swing.JButton botonEnviar;
    private javax.swing.JTextArea fieldMensaje;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaMensajes;
    private javax.swing.JLabel nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
